In [3]:
import numpy as np
from sympy import Matrix, symbols, linsolve
import math



In [14]:
n = 2
k = 2
q = 7
deg_Q = n+k-1
deg_E = k
deg_P = n-1

recieve_pts = [(1,5), (2,3), (3,4), (4,0), (5,3), (6,6)]
A = [[0 for _ in range(n + 2 * k)] for _ in range(n + 2 * k)]
B = [0 for pt in recieve_pts]

for i in range(n + 2 * k):
    for j in range(deg_Q + 1):
        A[i][j] = math.pow(recieve_pts[i][0], deg_Q - j)
        A[i][j] = int(A[i][j] % q)
    for k in range(deg_E):
        A[i][deg_Q + 1 + k] = -math.pow(recieve_pts[i][0], deg_E - 1 - k) * recieve_pts[i][1]
        A[i][deg_Q + 1 + k] = int(A[i][deg_Q + 1 + k] % q)

for i in range(len(B)):
    B[i] = int(math.pow(recieve_pts[i][0], deg_E) * recieve_pts[i][1] % q)

In [20]:
A

array([[1, 1, 1, 1, 2, 2],
       [1, 4, 2, 1, 1, 4],
       [6, 2, 3, 1, 2, 3],
       [1, 2, 4, 1, 0, 0],
       [6, 4, 5, 1, 6, 4],
       [6, 1, 6, 1, 6, 1]])

In [21]:
B

array([5, 5, 1, 0, 5, 6])

In [23]:
A = np.array(A)
B = np.array(B)
print(np.linalg.det(A))
# Solve for x
x = np.linalg.solve(A, B)
print(x)

209.99999999999994
[-2.13333333 -4.          3.         -1.86666667  0.33333333  4.66666667]


In [26]:
a3, a2, a1, a0, b1, b0 = symbols('a3 a2 a1 a0 b1 b0')

# System of equations converted to the form Ax = B
A = Matrix(A)

B = Matrix(B)

# Modulo 7 system, solving the equations
solution = linsolve((A, B), a3, a2, a1, a0, b1, b0 )